export const REQUEST_COMMENTS_INIT = 'REQUEST_COMMENTS_INIT';
export const REQUEST_COMMENTS_SUCCESS = 'REQUEST_COMMENTS_SUCCESS';
export const REQUEST_COMMENTS_ERROR = 'REQUEST_COMMENTS_ERROR';
export const SET_COMMENTS_ARE_SHOWN = 'SET_COMMENTS_ARE_SHOWN';