export const REQUEST_USERS_INIT = 'REQUEST_USERS_INIT';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_ERROR = 'REQUEST_USERS_ERROR';
export const SELECT_USER = 'SELECT_USER';
export const CLEAR_USER = 'CLEAR_USER';